### ISSUE TITLE
Spelling in code blocks

### ISSUE THREAD

**Issue by ChrisChinchilla** [avoiney/linter-spell-rst#1]
Well hello, thanks for the package.

Should it respect code blocks and not spell check them? It's not working for me :(

**Comment by avoiney** [comment]
Hello,

Thanks for reporting. 
It seems that the only language code scope I ask to not check spell is **python**. I will add other languages too.

Stay tuned,

**Comment by ChrisChinchilla** [comment]
@avoiney Excellent, thanks :)

**Comment by avoiney** [comment]
Hello @ChrisChinchilla,

I just released a minor version to add spellcheck exceptions for RST known embedded source.

I hope this will fix your issue !

Cheers,

**Comment by ChrisChinchilla** [comment]
@avoiney Sorry for the delay. Can confirm this works now.
